### ISSUE TITLE
Can't add databases

### ISSUE THREAD

**Issue by bch80** [JSSolutions/Databazel#29]
Hello,

I just installed databazel on a Kubuntu 16.10 computer.
During installation I saw those warnings:
`npm WARN formsy-material-ui@0.4.3 requires a peer of material-ui@^0.15.0 but none was installed.
npm WARN react-addons-test-utils@15.5.1 requires a peer of react-dom@^15.4.2 but none was installed.
npm WARN react-addons-transition-group@15.5.2 requires a peer of react@^15.4.2 but none was installed.
databazel.sh: 27: databazel.sh: java: not found
...
App running at: http://localhost:3000/    
`
but then it seemed to be working to login and create a new dashboard. I just can't add a database. In the console I see another error whilst using Databazel:
`I20170528-12:12:46.740(8)? Exception in callback of async function: TypeError: Cannot read property 'statusCode' of undefined
I20170528-12:12:46.740(8)?     at server/lib/quasar.js:87:19
I20170528-12:12:46.740(8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)`

Are there some version conflicts on my system or similar?

**Comment by uapasha** [comment]
Hi, @Chris8080!
This message means that you are not running `quasar`, which is required by the Databazel. 
Can you please provide full output of the `databazel.sh` script so we can make changes? It should've installed and launched quasar for you. 

Meanwhile, you can follow these instructions to successfully start Databazel: 
1) Make sure you have java installed
```
sudo apt-get update
which java && echo "java found" || sudo apt-get -y install default-jre
```
2) Download quasar distribution
`  curl -L https://github.com/quasar-analytics/quasar/releases/download/v11.4.5-quasar-web/quasar-web-assembly-11.4.5.jar -o ../quasar.jar;
`
3) Launch quasar 
`java -jar ../quasar.jar -c config/quasar.json &`

4) Launch Databazel
`meteor run --settings config/settings.json`
